
CREATE DATABASE IF NOT EXISTS nome_do_banco;

USE nome_do_banco;


CREATE TABLE IF NOT EXISTS tabela_exemplo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);